const express = require('express');
const router = express.Router();

// @InterfaceID: API-GET-QueryStations
router.get('/api/stations', (req, res) => {
  const { keyword } = req.query;
  const stations = [
    { name: "北京", code: "BJP" },
    { name: "北京南", code: "VNP" },
    { name: "北京西", code: "BXP" },
    { name: "上海", code: "SHH" },
    { name: "上海虹桥", code: "AOH" },
    { name: "上海南", code: "SNH" },
    { name: "广州", code: "GZQ" },
    { name: "广州南", code: "IZQ" },
    { name: "深圳", code: "SZQ" },
    { name: "深圳北", code: "IOQ" },
    { name: "成都", code: "CDW" },
    { name: "成都东", code: "ICW" },
    { name: "重庆", code: "CQW" },
    { name: "重庆西", code: "CXW" },
    { name: "杭州", code: "HZH" },
    { name: "杭州东", code: "HGH" },
    { name: "南京", code: "NJH" },
    { name: "南京南", code: "NKH" },
    { name: "西安", code: "XAY" },
    { name: "西安北", code: "EAY" },
    { name: "武汉", code: "WHN" },
    { name: "长沙", code: "CSQ" },
    { name: "长沙南", code: "CWQ" },
  { name: "郑州", code: "CGO" },
  { name: "合肥", code: "HFE" },
  { name: "济南", code: "TNA" },
  { name: "天津", code: "TSN" },
  { name: "南昌", code: "KHN" },
  { name: "福州", code: "FOC" },
  { name: "厦门", code: "XMN" },
  { name: "青岛", code: "TAO" },
  { name: "昆明", code: "KMG" },
  { name: "贵阳", code: "KWE" },
  { name: "兰州", code: "LHW" },
  { name: "南宁", code: "NNG" },
  { name: "沈阳", code: "SHE" },
  { name: "大连", code: "DLC" },
  { name: "哈尔滨", code: "HRB" },
  { name: "长春", code: "CGQ" },
  { name: "石家庄", code: "SJW" },
  { name: "太原", code: "TYN" },
  { name: "乌鲁木齐", code: "URC" },
  { name: "呼和浩特", code: "HET" },
  { name: "银川", code: "INC" },
  { name: "拉萨", code: "LXA" },
  { name: "海口", code: "HAK" },
  { name: "三亚", code: "SYX" },
  { name: "苏州", code: "SZV" },
  { name: "无锡", code: "WUX" },
  { name: "宁波", code: "NGB" },
  { name: "温州", code: "WNZ" },
  { name: "嘉兴", code: "JAX" },
  { name: "绍兴", code: "SXS" },
  { name: "台州", code: "HYN" },
  { name: "金华", code: "JIA" },
  { name: "舟山", code: "ZOS" },
  { name: "泉州", code: "JJN" },
  { name: "莆田", code: "PTD" },
  { name: "漳州", code: "ZGD" },
  { name: "汕头", code: "SWA" },
  { name: "揭阳", code: "SWA" },
  { name: "佛山", code: "FUO" },
  { name: "东莞", code: "DGG" },
  { name: "中山", code: "ZSN" },
  { name: "珠海", code: "ZUH" },
  { name: "惠州", code: "HUZ" },
  { name: "江门", code: "JMY" },
  { name: "肇庆", code: "ZAQ" },
  { name: "南通", code: "NTG" },
  { name: "扬州", code: "YTY" },
  { name: "泰州", code: "YTY" },
  { name: "盐城", code: "YNZ" },
  { name: "徐州", code: "XUZ" },
  { name: "连云港", code: "LYG" },
  { name: "淮安", code: "HIA" },
  { name: "宿迁", code: "SUQ" },
  { name: "洛阳", code: "LYA" },
  { name: "开封", code: "KFO" },
  { name: "邯郸", code: "HDG" },
  { name: "保定", code: "BDI" },
  { name: "唐山", code: "TSN" },
  { name: "秦皇岛", code: "BPE" },
  { name: "廊坊", code: "LFX" },
  { name: "烟台", code: "YNT" },
  { name: "威海", code: "WEH" },
  { name: "潍坊", code: "WEF" },
  { name: "泰安", code: "TAD" },
  { name: "淄博", code: "ZBW" },
  { name: "日照", code: "RIZ" },
  { name: "临沂", code: "LYI" },
  { name: "德州", code: "DZQ" },
  { name: "聊城", code: "LCG" },
  { name: "济宁", code: "JNG" },
  { name: "曲靖", code: "JGS" },
  { name: "玉溪", code: "YXI" },
  { name: "丽江", code: "LJG" },
  { name: "大理", code: "DLU" },
  { name: "西宁", code: "XNN" },
  { name: "咸阳", code: "XIY" },
  { name: "宝鸡", code: "BAJ" },
  { name: "延安", code: "ENY" },
  { name: "榆林", code: "UYN" }
  ];
  if (!keyword) {
    return res.json(stations.map(s => s.name));
  }
  const filteredStations = stations
    .filter(station => station.name.includes(keyword) || station.code.toLowerCase().includes(keyword.toLowerCase()))
    .map(s => s.name);
  res.json(filteredStations);
});

module.exports = router;